import { TokenType } from './design-token';
import { DesignTokenDecl, DESIGN_TOKENS } from './manifest';

/** Where the generated block is written, relative to the repo root. */
export const DESIGN_TOKEN_PROPERTIES_PATH = 'libs/web-styles/src/tokens/design-token-properties.css';

/** The command that rewrites it, quoted back at whoever let the two drift apart. */
export const GENERATE_COMMAND = 'pnpm tokens:generate';

/**
 * The `@property` syntax each token type registers under, or `null` for a type CSS cannot describe:
 * Properties & Values offers no shadow or font-stack component, and an `<image>` `initial-value` must
 * be computationally independent, which a gradient built from `var()` stops cannot be.
 */
const SYNTAX: Readonly<Record<TokenType, string | null>> = {
  color: '<color>',
  number: '<number>',
  length: '<length>',
  time: '<time>',
  easing: null,
  shadow: null,
  gradient: null,
  'font-pairing': null,
};

/** The tokens the `@property` block registers — a type CSS can describe, and no opt-out. */
export function registeredTokens(): readonly DesignTokenDecl[] {
  return DESIGN_TOKENS.filter((decl) => !decl.unregistered && SYNTAX[decl.type] !== null);
}

/**
 * The `@property` registration block, generated from the manifest (ADR-0075).
 *
 * Registration is what makes a token resolve: an unregistered custom property answers
 * `getPropertyValue` with its raw declaration, and three Canvas renderers hand exactly that to a 2D
 * drawing context. Everything inherits — the tokens are declared at the root and read below it.
 */
export function designTokenPropertyBlock(): string {
  const rules = registeredTokens().map(
    (decl) =>
      `@property ${decl.name} {\n` +
      `  syntax: '${SYNTAX[decl.type]}';\n` +
      `  inherits: true;\n` +
      `  initial-value: ${decl.initial};\n` +
      `}`,
  );
  return [
    '/*',
    ` * GENERATED by \`${GENERATE_COMMAND}\` from libs/web-styles/src/tokens/manifest.ts — do not edit.`,
    ' * The `@property` half of the token contract (ADR-0075).',
    ' */',
    ...rules,
    '',
  ].join('\n');
}
