import { TokenType } from './design-token';
import { DesignTokenDecl, DESIGN_TOKENS, SETTABLE_TOKENS } from './manifest';

/** Where the generated block is written, relative to the repo root. */
export const DESIGN_TOKEN_PROPERTIES_PATH = 'libs/web-styles/src/tokens/design-token-properties.css';

/** The pre-paint replay's allowlist is generated into this file too (ADR-0076). */
export const PRE_PAINT_REPLAY_PATH = 'apps/web/src/index.html';

/** Quoted in the drift specs' failure messages, so the fix arrives with the failure. */
export const GENERATE_COMMAND = 'pnpm tokens:generate';

/**
 * A run of generated lines fenced inside a committed file, so the generator rewrites it in place and
 * leaves the hand-written rest alone. The path is carried because a missing fence has to fail by name.
 */
export interface FencedRegion {
  readonly path: string;
  readonly open: string;
  readonly close: string;
}

/** Fences the generated allowlist inside {@link PRE_PAINT_REPLAY_PATH}. */
const ALLOWLIST_REGION: FencedRegion = {
  path: PRE_PAINT_REPLAY_PATH,
  open: '/* GENERATED — design-token allowlist */',
  close: '/* END GENERATED */',
};

/** Where a region's fences sit in `text`, and the indentation the opening one carries. */
function boundsOf(region: FencedRegion, text: string): { start: number; end: number; indent: string } {
  const open = text.indexOf(region.open);
  const close = open === -1 ? -1 : text.indexOf(region.close, open);
  if (open === -1 || close === -1) throw new Error(`${region.path} is missing the ${region.open} fence`);
  const indent = text.slice(text.lastIndexOf('\n', open) + 1, open);
  return { start: open - indent.length, end: close + region.close.length, indent };
}

/**
 * `text` with the region re-rendered between its fences. `render` writes the fences too, so the one
 * function knows where they go — and it is given the indentation the file chose rather than one this
 * module guesses.
 */
export function withFencedRegion(region: FencedRegion, text: string, render: (indent: string) => string): string {
  const { start, end, indent } = boundsOf(region, text);
  return text.slice(0, start) + render(indent) + text.slice(end);
}

/** What `text` actually holds between the fences — read back rather than re-rendered. */
export function fencedRegionIn(region: FencedRegion, text: string): string {
  const { start, end } = boundsOf(region, text);
  return text.slice(start, end);
}

/**
 * The `@property` syntax each token type registers under, or `null` for a type CSS cannot describe:
 * Properties & Values offers no shadow or font-stack component, and an `<image>` `initial-value` must
 * be computationally independent, which a gradient built from `var()` stops cannot be.
 */
export const SYNTAX: Readonly<Record<TokenType, string | null>> = {
  color: '<color>',
  number: '<number>',
  length: '<length>',
  time: '<time>',
  easing: null,
  shadow: null,
  gradient: null,
  'font-pairing': null,
};

/**
 * The tokens the `@property` block registers — the manifest's `unregistered` flag decides, alone.
 *
 * A type with no syntax cannot be registered either, but reading both here would leave two mechanisms
 * disagreeing about who owns the exception; ADR-0075 wants it declared. `property-block.spec.ts` holds
 * the flag and {@link SYNTAX} to each other so an unflagged shadow fails rather than registering.
 */
export function registeredTokens(): readonly DesignTokenDecl[] {
  return DESIGN_TOKENS.filter((decl) => !decl.unregistered);
}

/**
 * The `@property` registration block, generated from the manifest (ADR-0075).
 *
 * Registration is what makes a token resolve: an unregistered custom property answers
 * `getPropertyValue` with its raw declaration, and three Canvas renderers hand exactly that to a 2D
 * drawing context. Everything inherits — the tokens are declared at the root and read below it.
 */
export function designTokenPropertyBlock(): string {
  const rules = registeredTokens().map(
    (decl) =>
      `@property ${decl.name} {\n` +
      `  syntax: '${SYNTAX[decl.type]}';\n` +
      `  inherits: true;\n` +
      `  initial-value: ${decl.initial};\n` +
      `}`,
  );
  return [
    '/*',
    ` * GENERATED by \`${GENERATE_COMMAND}\` from libs/web-styles/src/tokens/manifest.ts — do not edit.`,
    ' * The `@property` half of the token contract (ADR-0075).',
    ' */',
    ...rules,
    '',
  ].join('\n');
}

/**
 * The pre-paint replay's name fence (ADR-0076), spliced into `index.html` by the same generator.
 *
 * The replay runs before Angular, so `declaredOnly` cannot reach it: without this the cache decides
 * which custom properties land on the root, and a `url()` on an unregistered name has nothing to
 * discard it. Fenced on {@link SETTABLE_TOKENS} rather than the whole manifest, so the cache admits no
 * more than the server's write choke point does. Split from one string because the names as an array
 * literal are mostly punctuation.
 */
export function designTokenAllowlistScript(indent = '        '): string {
  const names = SETTABLE_TOKENS.map((decl) => decl.name).join(',');
  return [
    `${indent}${ALLOWLIST_REGION.open}`,
    `${indent}var ALLOWED = '${names}'.split(',');`,
    `${indent}${ALLOWLIST_REGION.close}`,
  ].join('\n');
}

/** {@link PRE_PAINT_REPLAY_PATH}'s contents with the allowlist re-spliced between its fences. */
export function withDesignTokenAllowlist(html: string): string {
  return withFencedRegion(ALLOWLIST_REGION, html, designTokenAllowlistScript);
}

/**
 * The names the committed replay actually fences on — read back rather than re-rendered, because the
 * generator writes through Prettier and its wrapping is not this module's to predict.
 */
export function allowlistIn(html: string): readonly string[] {
  return [...fencedRegionIn(ALLOWLIST_REGION, html).matchAll(/'([^']*)'/g)]
    .flatMap((quoted) => quoted[1].split(','))
    .filter((name) => name !== '');
}
